version: '3.9'

services:
  ft_api:
    build: ./api
    volumes:
      - ./api/src:/usr/local/api
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: admin
      MONGO_PASS: admin
    ports:
      - "8000:8000"
      - "4444:4444"  # rpdb
    networks:
      - ft-network
    depends_on:
      - ft_mongodb
  ft_front:
    build: ./front
    volumes:
      - ./front:/usr/local/front
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - ft-network
  ft_mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_ROOT_DATABASE=admin
    volumes:
      - ft-vol-mongodb:/data/db
    networks:
      - ft-network

volumes:
  ft-vol-api:
  ft-vol-front:
  ft-vol-mongodb:

networks:
  ft-network:
    name: ft-network
    driver: bridge
