version: '3.9'

services:
  api:
    build: ./api
    volumes:
      - ./api/src:/usr/local/api
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    networks:
      - ft-network
  front:
    build: ./front
    volumes:
      - ft-vol-front:/usr/local/front
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - ft-network
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_ROOT_DATABASE=admin
    volumes:
      - ft-vol-mongodb:/data/db
    networks:
      - ft-network

volumes:
  ft-vol-api:
  ft-vol-front:
  ft-vol-mongodb:

networks:
  ft-network:
    name: ft-network
    driver: bridge
